### ISSUE TITLE
The mapping between files in two images

### ISSUE THREAD

**Issue by SilverBeats** [AmirAbaskohi/SemEval2022-Task6-Sarcasm-Detection#2]
![image](https://user-images.githubusercontent.com/39233532/224488124-9fb4233c-19ea-447f-8dbd-18d5bd498e9c.png)
![image](https://user-images.githubusercontent.com/39233532/224488126-718ef8c0-0e4d-4d4a-838c-5019b97e4448.png)

**Comment by AmirAbaskohi** [comment]
Hello,

Sorry for my late response.
Thank you for letting us know about the issue in naming our files. Here is the mapping:

| **File Name** |          **Dataset**         |
|:-------------:|:----------------------------:|
|     train1    | Sarcasm Headlines Dataset V1 |
|     train2    | Sarcasm Headlines Dataset V2 |
|     train3    |     Twitter News Dataset     |
|     train4    |     Sentiment 140 Dataset    |
|     train5    |             SPIRS            |
|     train6    | Twitter US Airline Sentiment |
